cabal-version:       2.4
name:                bridge-webkit
version:             0.1.0.0
synopsis:            WebKit-based GUI for the Rubber Bridge Game
description:         A beautiful graphical interface for the Haskell Rubber Bridge game using webkit-haskell
license:             Apache-2.0
license-file:        ../APACHE_LICENSE-2.0.txt
author:              Mark Watson
maintainer:          markw@markwatson.com
build-type:          Simple

library
  exposed-modules:     BridgeWebKit.Parsing
  build-depends:       base >= 4.7 && < 5
                     , aeson >= 1.0
                     , bridge-game
  hs-source-dirs:      src
  default-language:    Haskell2010
  ghc-options:         -Wall

executable bridge-webkit
  main-is:             Main.hs
  hs-source-dirs:      app
  build-depends:       base >= 4.7 && < 5
                     , containers >= 0.6
                     , random >= 1.1
                     , aeson >= 1.0
                     , bytestring >= 0.10
                     , text >= 1.2
                     , directory >= 1.3
                     , bridge-game
                     , webkit-haskell
                     , bridge-webkit
  default-language:    Haskell2010
  ghc-options:         -threaded -rtsopts -with-rtsopts=-N -Wall

test-suite bridge-webkit-test
  type:                exitcode-stdio-1.0
  main-is:             Spec.hs
  hs-source-dirs:      test
  build-depends:       base
                     , aeson
                     , bytestring
                     , bridge-game
                     , bridge-webkit
                     , hspec
  default-language:    Haskell2010
  ghc-options:         -Wall
