cabal-version:       2.4
name:                SimpleRDF
version:             0.1.0.0
synopsis:            An in-memory RDF store and SPARQL engine
description:         A simple demonstration of Graph pattern matching using the List Monad.
license:             MIT
author:              Author Name
maintainer:          email@example.com
category:            Database
build-type:          Simple

library
  exposed-modules:     SimpleRDF
  hs-source-dirs:      src
  build-depends:       base >= 4.12 && < 5
                     , containers
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings
                       DeriveGeneric
  ghc-options:         -Wall -O2

executable simple-rdf
  main-is:             Simple.hs
  hs-source-dirs:      app
  build-depends:       base >= 4.12 && < 5
                     , containers
                     , SimpleRDF
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings
  ghc-options:         -Wall -O2

executable simple-rdf-with-sparql
  main-is:             WithSPARQL.hs
  hs-source-dirs:      app
  build-depends:       base >= 4.12 && < 5
                     , containers
                     , SimpleRDF
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings
  ghc-options:         -Wall -O2

test-suite simple-rdf-test
  type:                exitcode-stdio-1.0
  main-is:             Spec.hs
  hs-source-dirs:      test
  build-depends:       base
                     , containers
                     , SimpleRDF
                     , hspec
  default-language:    Haskell2010
  default-extensions:  OverloadedStrings
